# Generated by Django 4.0.3 on 2022-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
