# Generated by Django 4.0.3 on 2022-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0002_remove_post_content_post_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.CharField(default='surname', max_length=100),
            preserve_default=False,
        ),
    ]
