# Generated by Django 4.0.3 on 2022-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0003_remove_post_datetime_post_name_post_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
