# Generated by Django 3.0.5 on 2022-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0005_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
