# Generated by Django 4.0.3 on 2022-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_name',
            field=models.CharField(default='pre', max_length=100),
            preserve_default=False,
        ),
    ]
