# Generated by Django 4.0.3 on 2022-03-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0010_post_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
