# Generated by Django 4.0.3 on 2022-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0011_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
