# Generated by Django 4.0.3 on 2022-03-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacheca', '0012_alter_post_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
